# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Playground
subtitle: A place to mess around.
description: >- # this means to ignore newlines until "baseurl:"
  My first experiance with jekyll. Github is pretty awesome.
author: Courd Headman
email: admin@courdh.com
avatar: assets/avatar.gif

# You'll want to customize url and baseurl for your own site:
baseurl: "/playground" # the subpath of your site, e.g. /blog
url: "https://coolcourd.github.io" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
instagram_url: https://www.instagram.com/coolcourd/
linkedin_url: https://www.linkedin.com/in/courd-headman-a3a8018b/
github_url: https://github.com/coolcourd
stackoverflow_url: https://stackoverflow.com/users/7062226/courd-headman

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: coolcourd/jekyll-theme-prologue
collections: [sections]